### PR TITLE
Updated scrollTo and jQuery for Chrome 61 compatibility

### PR DESCRIPTION
**Pull request by colega**
`scrollTo` has to be updated in order to be compatible with Chrome 61: https://github.com/flesler/jquery.scrollTo/issues/164
At the same time, `scrollTo` required a `jQuery` update.

Also moved libs to `js/libs` folder.

### CODE REVIEW

**Comment by shekhzyaul** [comment]
I also Have the Same Problum in my website . its not working in chrome 

[Link](http://demo.wpshopmart.com/coming-soon-pro-plugin-demo-template7-slideshow/)

**Comment by colega** [comment]
This solves https://github.com/zehfernandes/jquery.fullContent/issues/14
See the solution there.

**Comment by shekhzyaul** [comment]
i updated both but its not working

**Comment by shekhzyaul** [comment]
IT  Work's  i updated both the scrollTo and localscroll plugins  Thanks  :1st_place_medal:

**Pull request merged**
